"""empty message

Revision ID: 2dadff3c2b25
Revises: 0db161dbf8d6
Create Date: 2021-07-04 17:33:31.559489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dadff3c2b25'
down_revision = '0db161dbf8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bac_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cov', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bac_points', schema=None) as batch_op:
        batch_op.drop_column('cov')

    # ### end Alembic commands ###
