"""empty message

Revision ID: 95394544772e
Revises: 0db161dbf8d6
Create Date: 2021-06-04 12:18:14.691125

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '95394544772e'
down_revision = '0db161dbf8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_bp_gp')
    op.create_table('mappings_bp_gp',
                    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('uuid', sa.String(), nullable=False),
                    sa.Column('point_uuid', sa.String(length=80), nullable=False),
                    sa.Column('mapped_point_uuid', sa.String(), nullable=False),
                    sa.Column('point_name', sa.String(length=80), nullable=False),
                    sa.Column('mapped_point_name', sa.String(length=80), nullable=False),
                    sa.Column('mapping_state', sa.Enum('MAPPED', 'BROKEN', name='mappingstate'), server_default="MAPPED"),
                    sa.ForeignKeyConstraint(['point_uuid'], ['bac_points.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('mapped_point_uuid'),
                    sa.UniqueConstraint('mapped_point_uuid')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_bp_gp')
    op.create_table('mappings_bp_gp',
                    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('uuid', sa.String(), nullable=False),
                    sa.Column('bacnet_point_uuid', sa.String(length=80), nullable=False),
                    sa.Column('generic_point_uuid', sa.String(), nullable=False),
                    sa.Column('bacnet_point_name', sa.String(length=80), nullable=False),
                    sa.Column('generic_point_name', sa.String(length=80), nullable=False),
                    sa.ForeignKeyConstraint(['bacnet_point_uuid'], ['bac_points.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('generic_point_uuid'),
                    sa.UniqueConstraint('generic_point_uuid')
                    )

    # ### end Alembic commands ###
