"""empty message

Revision ID: 0db161dbf8d6
Revises: e593819d066a
Create Date: 2021-05-24 14:19:07.777094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '0db161dbf8d6'
down_revision = 'e593819d066a'
branch_labels = None
depends_on = None

session = Session(bind=op.get_bind())
session.execute('PRAGMA foreign_keys = OFF;')
session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bac_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('OWN', 'MAPPING', name='sources'), server_default="OWN"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bac_points', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
