"""empty message

Revision ID: 1d51de75aca6
Revises: 02c1a0da274b
Create Date: 2022-03-24 16:04:36.887596

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1d51de75aca6'
down_revision = '02c1a0da274b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bac_points', schema=None) as batch_op:
        batch_op.create_unique_constraint('UC_address', ['address'])
    with op.batch_alter_table('bac_points', schema=None) as batch_op:
        batch_op.drop_constraint('UC_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
